import fs from "fs";
import path from "path";
import loadEnv from "../loadEnv";

const loadedEnv = loadEnv();

if (!loadedEnv.gistId) {
  throw new Error("Missing GIST_ID");
}

const configContent = `
// This file is generated automatically, do not edit directly!
// Generated at ${new Date().toISOString()}
// This file is generated by setup/createConfig.ts to load environment variables from .env file and export them as a config object for the app

import envType from "../../types/envType";

const config = ${JSON.stringify(loadedEnv, null, 2)} as envType;

export default config;
`;

const configFilePath = path.resolve(__dirname, "../config.ts");

fs.writeFileSync(configFilePath, configContent);

console.log("config.ts file created successfully!");
