const envDefaults = {
  STORE_METHOD: "gist",
  FILENAME: "WEEB.svg",
  SIZE: "full",
  STYLE: "default",

  PLUGIN_MAL_SECTIONS: "stats_simple, anime_favorites, last_activity",
  PLUGIN_MAL_LAST_ACTIVITY_MAX: "5",
  PLUGIN_MAL_ANIME_FAVORITES_MAX: "5",
  PLUGIN_MAL_CHARACTERS_FAVORITES_MAX: "5",
  PLUGIN_MAL_PEOPLE_FAVORITES_MAX: "5",
  PLUGIN_MAL_MANGA_FAVORITES_MAX: "5",

  PLUGIN_MAL_STATISTICS_TITLE: "Statistics",
  PLUGIN_MAL_ANIME_BAR_TITLE: "Anime Statistics",
  PLUGIN_MAL_MANGA_BAR_TITLE: "Manga Statistics",
  PLUGIN_MAL_STATS_SIMPLE_TITLE: "Simple Statistics",
  PLUGIN_MAL_ANIME_FAVORITES_TITLE: "Anime Favorites",
  PLUGIN_MAL_MANGA_FAVORITES_TITLE: "Manga Favorites",
  PLUGIN_MAL_PEOPLE_FAVORITES_TITLE: "People Favorites",
  PLUGIN_MAL_CHARACTERS_FAVORITES_TITLE: "Character Favorites",
  PLUGIN_MAL_LAST_ACTIVITY_TITLE: "Last Activity",

  PLUGIN_LASTFM_SECTIONS: "top_tracks",
  PLUGIN_LASTFM_RECENTTRACKS_MAX: "6",
  PLUGIN_LASTFM_TOPARTISTS_MAX: "5",
  PLUGIN_LASTFM_TOPALBUMS_MAX: "5",
  PLUGIN_LASTFM_TOPTRACKS_MAX: "5",
  PLUGIN_LASTFM_TOPTRACKS_TITLE: "Top Tracks",
  PLUGIN_LASTFM_TOPARTISTS_TITLE: "Top Artists",
  PLUGIN_LASTFM_TOPALBUMS_TITLE: "Top Albums",
  PLUGIN_LASTFM_RECENTTRACKS_TITLE: "Recent Tracks",
  PLUGIN_LASTFM_STATISTICS_TITLE: "Statistics",
};

export default envDefaults;
