const envDefaults = {
  STORE_METHOD: "gist",
  FILENAME: "WEEB.svg",
  SIZE: "full",

  PLUGIN_MAL_STYLE: "default",
  PLUGIN_MAL_SECTIONS: "stats_simple, anime_favorites, last_activity",
  PLUGIN_MAL_LASTUPDATES_MAX: "5",
  PLUGIN_MAL_ANIME_FAVORITES_MAX: "5",
  PLUGIN_MAL_CHARACTERS_FAVORITES_MAX: "5",
  PLUGIN_MAL_PEOPLE_FAVORITES_MAX: "5",
  PLUGIN_MAL_MANGA_FAVORITES_MAX: "5",

  PLUGIN_LASTFM_STYLE: "default",
  PLUGIN_LASTFM_SECTIONS: "top_tracks",
  PLUGIN_LASTFM_RECENTTRACKS_MAX: "6",
  PLUGIN_LASTFM_TOPARTISTS_MAX: "5",
  PLUGIN_LASTFM_TOPALBUMS_MAX: "5",
  PLUGIN_LASTFM_TOPTRACKS_MAX: "5",
};

export default envDefaults;
